# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .gitlab_runner_awsa import *
from .provider import *
from ._inputs import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "gitlab-runner-awsa",
  "mod": "index",
  "fqn": "pulumi_gitlab_runner_awsa",
  "classes": {
   "gitlab-runner-awsa:index:GitlabRunnerAwsa": "GitlabRunnerAwsa"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "gitlab-runner-awsa",
  "token": "pulumi:providers:gitlab-runner-awsa",
  "fqn": "pulumi_gitlab_runner_awsa",
  "class": "Provider"
 }
]
"""
)
