// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface S3CacheArgs {
    bucketName?: pulumi.Input<string>;
    path?: pulumi.Input<number>;
    serverAddress?: pulumi.Input<string>;
}

export interface TagMapArgs {
}

export interface VolumeArgsArgs {
    size?: pulumi.Input<number>;
    type?: pulumi.Input<string>;
}
